### ISSUE TITLE
Taking over the project

### ISSUE THREAD

**Issue by StrangeOne101** [jedk1/JedCore#1]
I know you aren't accepting PRs. I know you are no longer are updating this. So does that mean others have permission to update and redistribute it?

Credits will still go to you. It will simply be an updated version of the plugin available for everyone.

**Comment by jedk1** [comment]
Someone is way ahead of you. https://github.com/plushmonkey/JedCore
Id prefer if it wasn't redistributed except via github.

**Comment by StrangeOne101** [comment]
Alrighty.

**Comment by jedk1** [comment]
https://github.com/plushmonkey/JedCore/releases
For anyone looking at this in future who doesn't know how github works who is looking for a release version.
