### ISSUE TITLE
Having problems with most of the bending skills from JedCore plugin.

### ISSUE THREAD

**Issue by cisiluma02** [jedk1/JedCore#2]
Hey,
Since I upload the JedCore Plugin into my server there are lots of bugg which i still cant fix, First of all if air benders fly while they throw other people to air they don't take falling damage, other then that some of the skills don't work like how they supposed to work or don't work at all.suffocate skill makes particles and only gives slowness and blind effect when a player press shift on somebody so they need to press left click to deal damage, it cant happen in the same time if a player use suffocate skill but admins can do both in the same time so it works flawless with admins, I think there is something wrong with perms but I don't know what it is or how to fix it.

**Comment by connorhartley** [comment]
@cisiluma02 do not post the credentials of your account public here. I have removed the credentials from your message and sent them to Jed.

**Comment by jedk1** [comment]
Why does no one ever read the ReadMe. Specifically the bit that says I don't want to do anything with JedCore anymore, Sorry but I won't be helping.
